# Site settings
title: WG-school-at-UBC
description: > 
  Create a workshop website quick and easy! 
keywords: "workshops, websites, gh-pages"

# author settings for cc-by
author: WestGrid
github_username: evanwill
twitter_username: EvanPeterWill
pub_year: 2018

# add the full url for the github repository
repo: "https://github.com/razoumov/testSchool.git"

# add the full url for the repository's gh-pages
# hint: it's in the form https://username.github.io/repo-name
url: "https://razoumov.github.io/testSchool"

# add google analytics if desired (and uncomment in _includes/head.html)
google_analytics: 

# Build settings
markdown: kramdown

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav

theme: jekyll-theme-minimal